version: "3.9"

services:
  filestorage:
    build:
      context: ./FileStorageService
      dockerfile: Dockerfile
    container_name: filestorage
    ports:
      - "8081:8080"  
    restart: unless-stopped

  fileanalysis:
    build:
      context: ./FileAnalysisService
      dockerfile: Dockerfile
    container_name: fileanalysis
    ports:
      - "8082:8080"
    restart: unless-stopped

  apigateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    container_name: apigateway
    ports:
      - "8080:8080"
    depends_on:
      - filestorage
      - fileanalysis
    restart: unless-stopped
